name: Foxrain CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest
    env: 
      DB_URL: ${{secrets.DB_URL}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_PW: ${{secrets.DB_PW}}
      SECRET_USER: ${{secrets.SECRET_USER}}
      SECRET_ADMIN: ${{secrets.SECRET_ADMIN}}
      
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
